"""initial migration

Revision ID: ca39e748bdd4
Revises: 
Create Date: 2020-05-27 09:30:41.247447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca39e748bdd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=64), nullable=True),
    sa.Column('user_username', sa.String(length=64), nullable=True),
    sa.Column('user_role', sa.String(length=10), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_email'), 'users', ['user_email'], unique=True)
    op.create_index(op.f('ix_users_user_role'), 'users', ['user_role'], unique=False)
    op.create_index(op.f('ix_users_user_username'), 'users', ['user_username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_author', sa.Integer(), nullable=True),
    sa.Column('post_title', sa.String(length=100), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('post_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_author'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_index(op.f('ix_users_user_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_role'), table_name='users')
    op.drop_index(op.f('ix_users_user_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
